### ISSUE TITLE
[FEATURE] Implement ServerList features (Player Count & Running Status)

### ISSUE THREAD

**Issue by jordan-dalby** [JensvandeWiel/ArkAscendedServerManager#119]
**Describe the feature**
Currently, the ServerList page doesn't show the player count or running status (not implemented yet)

This should be changed.

**Comment by jordan-dalby** [comment]
This needs its label updating, I discovered it's a missing feature, not a bug.

**Comment by jordan-dalby** [comment]
This probably needs to wait until #87 goes in. IsRunning will be a useful bool.

**Comment by JensvandeWiel** [comment]
> This probably needs to wait until #87 goes in. IsRunning will be a useful bool.

@jordan-dalby if you want you can take this task over, if i was you i would probably start over :)

**Comment by jordan-dalby** [comment]
I'll take this over, I'll incorporate it with #119.
