### ISSUE TITLE
Add auto update system to self update

### ISSUE THREAD

**Issue by JensvandeWiel** [JensvandeWiel/ArkAscendedServerManager#12]
Blocked by [#11](https://github.com/JensvandeWiel/ArkAscendedServerManager/issues/11 ) because this need the releases to work and be able to get an executable from them. 

It should self update and not ship an extra binary that does this.

references:
https://github.com/minio/selfupdate
https://github.com/Vovan-VE/supaplex-levels-editor/blob/main/.github/workflows/release.yml

**Comment by ItsMePepijn** [comment]
I will look into this
