### ISSUE TITLE
[FEATURE] Auto-Save

### ISSUE THREAD

**Issue by jordan-dalby** [JensvandeWiel/ArkAscendedServerManager#121]
**Is your feature request related to a problem? Please describe.**
Servers currently do not automatically save.

**Describe the solution you'd like**
An auto-save feature, configurable.

**Describe alternatives you've considered**
Data backups (which should also be added as part of another ticket)

**Additional context**
n/a

**Comment by JensvandeWiel** [comment]
@jordan-dalby found an issue, when i enable auto save it's default value is 0 and you can not divide by zero :)
panic: runtime error: integer divide by zero

goroutine 38 [running]:
github.com/JensvandeWiel/ArkAscendedServerManager/server.(*ServerController).AutoSaveServers(0xc00006f080)
        C:/Users/Jens van de Wiel/MyProjects/ArkAscendedServerManager/server/server_controller.go:124 +0x488
github.com/JensvandeWiel/ArkAscendedServerManager/server.(*ServerController).RunAutoSaveTimers(0xc00006f080)
        C:/Users/Jens van de Wiel/MyProjects/ArkAscendedServerManager/server/server_controller.go:97 +0x5f
github.com/JensvandeWiel/ArkAscendedServerManager/server.(*ServerController).Startup(0xc00006f080, {0xe64190, 0xc00020bef0})
        C:/Users/Jens van de Wiel/MyProjects/ArkAscendedServerManager/server/server_controller.go:63 +0x305
main.main.func1({0xe64190, 0xc00020bef0})
        C:/Users/Jens van de Wiel/MyProjects/ArkAscendedServerManager/main.go:64 +0xae
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).Run.func3()
        C:/Users/Jens van de Wiel/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/windows/frontend.go:191 +0x57
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).Run in goroutine 1
        C:/Users/Jens van de Wiel/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/windows/frontend.go:189 +0x3a5
