### ISSUE TITLE
[BUG] MaxPlayers obsolete in the INI

### ISSUE THREAD

**Issue by xXFreeFunXx** [JensvandeWiel/ArkAscendedServerManager#141]
The specification of the MaxPlayers in the INI file has no influence on the slots. The slots are defined in the start command.

The MaxPlayers are also represented twice in the json and therefore in the INI file.

Extensively tested!

PS: Is there a reason for the Ragnarok section?
There will be something in the INI that has no purpose.
# json
![](https://cdn.discordapp.com/attachments/1106326089569148999/1177252909935775804/3EouKv84IR.png?ex=6571d536&is=655f6036&hm=2ca4e20d83964f46bccce6e8112250563b3638fab4bc1e1a87d3689e1a90aa08&)
# ini
![](https://cdn.discordapp.com/attachments/1106326089569148999/1177253314325389373/ug7Hch8YtH.png?ex=6571d596&is=655f6096&hm=a1574680ebf23a0f0e5860406c1896c58a77e7ee633f843f612c0d3197600b60&)

**Comment by JensvandeWiel** [comment]
it is obsolete but we will keep it because for (maybe) future support for ASE

**Comment by xXFreeFunXx** [comment]
That's great news that you want to support ASE in the future. I welcome it! 😀 

But I would like the manager to be able to differentiate between ASE and ASA.

I can understand keeping some things but these things will cause a lot of confusion.

It's just a suggestion if you want ASE compatibility. 😉
