### ISSUE TITLE
[BUG] Start command with space

### ISSUE THREAD

**Issue by xXFreeFunXx** [JensvandeWiel/ArkAscendedServerManager#142]
There are spaces in the start command. Has something been hidden perhaps?

By the way `?listen` has no effect.

![](https://cdn.discordapp.com/attachments/1106326089569148999/1177254114896392253/GHj8o5m8zE.png?ex=6571d655&is=655f6155&hm=78b133d9569a6c80c564f0316cfdf3dd210010fee16eecae91833865df145f13&)

**Comment by JensvandeWiel** [comment]
The spaces are there for a reason, they don't impact the workings, the "?listen" is kept for backwards compatibility for maybe ASE support
