### ISSUE TITLE
[FEATURE] Open Saved folder

### ISSUE THREAD

**Issue by xXFreeFunXx** [JensvandeWiel/ArkAscendedServerManager#145]
There is a button to open the installation directory. What I always missed in ASM was a button to open the Saved folder.
That's where you spend most of your time :grin:

`...\ShooterGame\Saved`

**Comment by JensvandeWiel** [comment]
I understand but how hard is it to go into one directory, I understand your reason but if we add buttons for everything like this the UI will get bloated.

**Comment by xXFreeFunXx** [comment]
I agree with you, it was just a suggestion. :relaxed:

**Comment by JensvandeWiel** [comment]
👍 please keep suggestions in the feedback channel in discord
