### ISSUE TITLE
[FEATURE] Networking custom IP

### ISSUE THREAD

**Issue by flames** [JensvandeWiel/ArkAscendedServerManager#168]
**Is your feature request related to a problem? Please describe.**
In "General Settings", "Networking", "IP Address" you can only select 0.0.0.0 / All and the actual interface IP. Please add "manual IP" with a text field.

**Describe the solution you'd like**
Possibility to bind to a custom defined IP address

**Describe alternatives you've considered**
-

**Additional context**
I am running ASA dedicated server behind NAT, but i have multiple static IPs on my WAN, which are assigned to servers/server roles.
In case of ASA i have a separate static WAN IP which is assigned in the firewall as outbound IP for that machine (including PTR/reverce DNS). So when it is possible to propagate that static IP instead of 0.0.0.0, the dedicated server is available in Game to join within seconds. With 0.0.0.0 it takes 3-5 minutes from start until it is visible in game.

Thanks in advance.
Whish you a merry crhistmas and a happy new year!

**Comment by JensvandeWiel** [comment]
as long if it is its own/virtual interface you should be able to use the ip

**Comment by flames** [comment]
Yes, i am using 0.0.0.0 currently. I see the connection stack is different in ASA vs ASE. Strange thing is, when i start the server w/o manager, it is nearly instantly visible in the game lobby. This is what made me think, that ASA server propagates the configured IP address to Epic, as ASE servers did with Steam (there was exactly that behaviour, when you don't propagate the real WAN IP to steam, it took up to 10 minutes after server start until it was visible/joinable via Steam or game lobby.
To avoid misunderstanding, my interface IP != WAN IP, it is a 1:1 NAT WAN IP -> server interface IP + outbound NAT server interface IP -> WAN IP. when i curl icanhazip.com on the server, it returns the corresponding WAN IP which is bound to the server, not my main WAN IP (as said, i have multiple WAN IPs, but those are not the interface IPs of the server, there is still NAT).
To check, if my assumption is right or wrong, i will test it soon with binding to the interface IP, instead of any.
Closing this Issue. If i can elaborate something more, will reopen it. Thanks!

**Comment by flames** [comment]
Ups, can't close my self :)
