### ISSUE TITLE
add button to open actual server files

### ISSUE THREAD

**Issue by Ivan0348** [JensvandeWiel/ArkAscendedServerManager#34]
The open servers button that is present now opens a folder with configs for servers in Local

**Comment by JensvandeWiel** [comment]
This is the intended function of that button, we can add this as a perver panel thing.

**Comment by Ivan0348** [comment]
can you assign me on this issue?

**Comment by JensvandeWiel** [comment]
for this you need to get the server specific config path this is the configpath +server + serverId
just use a link with file:///
