### ISSUE TITLE
Auto Remove Mod

### ISSUE THREAD

**Issue by xXFreeFunXx** [JensvandeWiel/ArkAscendedServerManager#48]
My server would not start today and always crashed.
After researching I found out the mod page is available but no files existed.
I had to remove the mod therefore.

My suggestion:
A check if the mod page and files exist.
If not, then the mod should be removed so that the server can start.
Maybe also as an optional feature to enable.
The removal of stacking or storage mods are always very dangerous.

**Comment by JensvandeWiel** [comment]
blocked until mods are supported https://github.com/JensvandeWiel/ArkAscendedServerManager/issues/22

**Comment by Ivan0348** [comment]
Or a warning message if mod files are missing so it wont start unit the users says it can remove the mods

**Comment by xXFreeFunXx** [comment]
If you press the button yourself but what about auto restarts?
