### ISSUE TITLE
Add 0.0.0.0 default interface back

### ISSUE THREAD

**Issue by Kaffiend** [JensvandeWiel/ArkAscendedServerManager#52]
Error Log
2023/11/01 22:35:12 ERR | Error unmarshalling config file: invalid character 'a' in string escape code
2023/11/01 22:35:12 ERR | Failed to get all servers C:\Users\ark_server\AppData\Local\ArkAscendedServerManager\Servers error: C:\Users\ark_server\AppData\Local\ArkAscendedServerManager\Servers does not exit
2023/11/01 22:35:16 ERR | Failed saving new server: Parsing server instance failed: Check failed: Ip address not found in system interfaces: 0.0.0.0
2023/11/01 22:35:16 ERR | Failed to get all servers C:\Users\ark_server\AppData\Local\ArkAscendedServerManager\Servers error: C:\Users\ark_server\AppData\Local\ArkAscendedServerManager\Servers does not exit
2023/11/01 22:35:16 ERR | Error saving server: Parsing server instance failed: Check failed: Ip address not found in system interfaces: 0.0.0.0
2023/11/01 22:35:31 ERR | Error saving server: Parsing server instance failed: Check failed: Ip address not found in system interfaces: 0.0.0.0
2023/11/01 22:42:14 ERR | Error saving server: Parsing server instance failed: Check failed: Ip address not found in system interfaces: 0.0.0.0
2023/11/01 22:42:21 ERR | Error saving server: Parsing server instance failed: Check failed: Ip address not found in system interfaces: 0.0.0.0
2023/11/01 22:42:24 ERR | C:\Users\ark_server\AppData\Local\ArkAscendedServerManager\Servers does not exit
2023/11/01 22:42:25 ERR | Failed to get all servers C:\Users\ark_server\AppData\Local\ArkAscendedServerManager\Servers error: C:\Users\ark_server\AppData\Local\ArkAscendedServerManager\Servers does not exit

**Comment by JensvandeWiel** [comment]
First, in your config file you need escape a '\' like this: '\\' thats why you  this error:
2023/11/01 22:35:12 ERR | Error unmarshalling config file: invalid character 'a' in string escape code

**Comment by JensvandeWiel** [comment]
I see there is a small bug and i will fix that asap, i will add 0.0.0.0 back as an option. For now when you make a server make sure you set a ip address.
