### ISSUE TITLE
Seperate the ark server process from the manager

### ISSUE THREAD

**Issue by ItsMePepijn** [JensvandeWiel/ArkAscendedServerManager#57]
When the servers are sub processes of the manager they  will stop if the manager ever crashes or gets closed. We want the manager to run seperately so you can restart or update it without having to worry about the servers themselves. 

For this to work the start/stop logic needs to be re-implented because it assumes the servers are sub-processes.

**Comment by JensvandeWiel** [comment]
is stale till at least beta
