### ISSUE TITLE
Server Install does not work on Windows Server 2016

### ISSUE THREAD

**Issue by mDeaders** [JensvandeWiel/ArkAscendedServerManager#76]
Currently, you can't install a server on Windows Server 2016, as the application uses ConPty (Windows Pseudo Console) which is not available on Windows Server 2016.

Looking forward to seeing your progress on this app!

**Comment by JensvandeWiel** [comment]
Sorry to say, but we can't support Windows server 2016, this is because it is missing a crucial part called Windows Pseudo Console.
You can maybe try to install it somehow with Windows SDK but success is not garanteed. If you can fix it please let me know as we will add it to the docs
