### ISSUE TITLE
Add a discord addon/interface in the app

### ISSUE THREAD

**Issue by JensvandeWiel** [JensvandeWiel/ArkAscendedServerManager#8]
Add a webhook integration for each server, for now only the backend should be made, since we don't have a server instance yet.

**Comment by August2211** [comment]
// SendToDiscord sends the given message to the webhook url
func SendToDiscord(message string, webhookUrl string) bool {

    body := map[string]string{
        "content": message,
    }

    jsonBody, err := json.Marshal(body)

    if err != nil {
        runtime.LogError(context.Background(), "Error marshalling body json: "+err.Error())
        return false
    }

    response, err := http.Post(webhookUrl, "application/json", bytes.NewBuffer(jsonBody))

    if err != nil {
        runtime.LogError(context.Background(), "Error sending message to discord: "+err.Error())
        return false
    }

    if response.StatusCode != 204 {
        runtime.LogError(context.Background(), "Error sending message to discord: "+response.Status)
        return false
    }

    return true
}

**Comment by JensvandeWiel** [comment]
I assigned it to you, i you could make a repo for this issue and add it there and make a pull request ill add it!
