### ISSUE TITLE
[FEATURE/BUG] Button to remove config.json when no server installed

### ISSUE THREAD

**Issue by Ivan0348** [JensvandeWiel/ArkAscendedServerManager#99]
**Is your feature request related to a problem? Please describe.**
When you click on add new server it creates a profile and a config.json file. But if you dont want a server you cant delete the profile till you install the server and click on the delete button.
![image](https://github.com/JensvandeWiel/ArkAscendedServerManager/assets/103519966/e0c31d36-800f-4e75-bf62-e6a4f64624d2)

**Describe the solution you'd like**
A delete profile button of some sort.

**Describe alternatives you've considered**
Deleting the profile folder

**Comment by JensvandeWiel** [comment]
@Ivan0348 do you want to make this?

**Comment by Ivan0348** [comment]
yes I can try

**Comment by JensvandeWiel** [comment]
you can look at the current implementation in administration page

**Comment by Ivan0348** [comment]
merged pr
